'use client'

import { Link2 } from 'lucide-react'

export interface BetBuilderSelection { market_name: string; label: string; probability: number; odds_estimate: number }
export interface BetBuilderProfile { profile: string; label: string; selections: BetBuilderSelection[]; combined_odds: number; combined_probability: number }
interface BetBuilderCardsProps { profiles: BetBuilderProfile[] }

const PROFILE_LABELS: Record<string, string> = { CONSERVATIVE: 'BAJA VARIANZA', MODERATE: 'RIESGO MEDIO', BOLD: 'ALTA VARIANZA', CAZADOR: '+EV MÁXIMO' }
function profileLabel(profile: string) { const upper = profile.toUpperCase(); return PROFILE_LABELS[upper] ?? (upper.includes('CONS') ? PROFILE_LABELS.CONSERVATIVE : PROFILE_LABELS.BOLD) }

export function BetBuilderCards({ profiles }: BetBuilderCardsProps) {
  if (!profiles.length) return <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No hay estrategias correlacionadas para este partido.</div>
  return <div className="flex flex-col gap-3"><div className="flex items-center gap-2"><span className="text-[10px] font-mono font-bold uppercase tracking-widest text-muted-foreground">ESTRATEGIAS CORRELACIONADAS</span><span className="h-px flex-1 bg-border/50" /><span className="font-mono text-[10px] text-muted-foreground">QUANT ENGINE</span></div><div className="grid gap-3 lg:grid-cols-3">{profiles.map((profile) => <div key={profile.profile} className="group relative flex flex-col gap-3 rounded-xl border border-border/60 bg-surface/30 p-4 transition-[border-color,background-color,transform] duration-200 ease-out hover:-translate-y-0.5 hover:border-primary/30 hover:bg-surface/60"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><span className="inline-flex rounded border border-border/60 bg-surface px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase text-muted-foreground">{profileLabel(profile.profile)}</span><p className="mt-1 truncate text-xs font-semibold text-foreground">{profile.label}</p></div><div className="text-right"><span className="block text-[9px] uppercase tracking-wider text-muted-foreground">Cuota</span><span className="font-mono text-lg font-bold tabular-nums text-foreground">{profile.combined_odds.toFixed(2)}</span></div></div><ul className="relative flex flex-col gap-2 border-y border-border/40 py-2">{profile.selections.map((selection, index) => <li key={selection.market_name} className="flex items-center gap-2"><span className="flex size-5 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-primary/10 font-mono text-[9px] text-primary">{index + 1}</span><span className="min-w-0 flex-1 truncate text-[11px] text-muted-foreground">{selection.label}</span><span className="shrink-0 font-mono text-xs font-semibold tabular-nums text-foreground">@{selection.odds_estimate.toFixed(2)}</span></li>)}</ul><div className="grid grid-cols-3 divide-x divide-border/40 rounded border border-border/50 bg-surface/40"><div className="px-2 py-1.5"><span className="block text-[9px] uppercase text-muted-foreground">Prob.</span><span className="font-mono text-xs font-semibold tabular-nums text-foreground">{(profile.combined_probability * 100).toFixed(0)}%</span></div><div className="px-2 py-1.5"><span className="block text-[9px] uppercase text-muted-foreground">Correl.</span><span className="font-mono text-xs font-semibold tabular-nums text-positive">+{Math.min(25, profile.selections.length * 7)}%</span></div><div className="px-2 py-1.5"><span className="block text-[9px] uppercase text-muted-foreground">¼ Kelly</span><span className="font-mono text-xs font-semibold tabular-nums text-foreground">{(profile.combined_probability * 100 * 0.25).toFixed(1)}%</span></div></div><div className="flex items-center gap-2 text-[10px] text-muted-foreground"><Link2 className="size-3 text-primary" /> Selecciones validadas como bloque correlacionado</div></div>)}</div></div>
}
